- name: Add MongoDB repository for RHEL
  yum_repository:
    name: mongodb-org
    description: MongoDB Repository
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    enabled: yes

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Start and enable MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started

- name: Create MongoDB data directory
  file:
    path: "{{ mongodb_data_path }}"
    state: directory
    owner: mongod
    group: mongod
    mode: '0755'

- name: Template the MongoDB config file
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart MongoDB

- name: Check if .mongoshrc.js file exists
  stat:
    path: /root/.mongoshrc.js
  register: mongorc_file

- name: Create MongoDB root user
  mongodb_user:
    database: admin
    user: "{{ mongodb_root_user }}"
    password: "{{ mongodb_root_password }}"
    roles: ["root"]
  when: not mongorc_file.stat.exists

- name: Deploy the MongoDB .mongoshrc.js file for the root user
  template:
    src: mongoshrc.js.j2
    dest: /root/.mongoshrc.js
    mode: '0600'
  notify:
    - Restart MongoDB

- name: Enable Auth in MongoDB config
  lineinfile:
    path: /etc/mongod.conf
    line: "security:\n authorization: enabled"
    insertafter: "^security:"
    state: present
    backup: yes
  notify: Restart MongoDB

