---
# tasks file for roles/webserver

- name: Install Node.JS and NPM
  ansible.builtin.yum:
    pkg:
      - nodejs
      - npm
    state: present

- name: Create app directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ users[0].name }}"  # Using users[0].name
    group: "{{ users[0].group }}"  # Using users[0].group
    mode: '0755'

- name: Install NPM packages
  ansible.builtin.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm_packages }}"

- name: Initialize a new React project
  ansible.builtin.command:
    cmd: "npx --yes create-react-app@latest {{ app_name }}"
    chdir: "{{ app_dir }}"
  args:
    creates: "{{ app_dir }}/{{ app_name }}"
  become: yes
  become_user: "{{ users[0].name }}"  # Using users[0].name

- name: Configure React to listen on 0.0.0.0
  ansible.builtin.lineinfile:
    path: "{{ app_dir }}/{{ app_name }}/.env"
    line: "HOST=0.0.0.0"
    create: yes

- name: Deploy the custom css file
  ansible.builtin.copy:
    src: App.css
    dest: "{{ app_dir }}/{{ app_name }}/src/App.css"
    mode: '0644'
  when: deploy_custom_page

- name: Deploy custom app.js
  ansible.builtin.template:
    src: App.js.j2
    dest: "{{ app_dir }}/{{ app_name }}/src/App.js"
    mode: '0644'
    variable_start_string: "{[%"
    variable_end_string: "%]}"
  when: deploy_custom_page

- name: Start the React server with PM2
  ansible.builtin.command:
    cmd: "/usr/local/bin/pm2 start npm -- run start"
    chdir: "{{ app_dir }}/{{ app_name }}"
